version: "3"
services:
  springapp:
    build: src
    container_name: basetask
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/addresses
    ports:
      - 8000:8080
    restart: always
    depends_on:
      - db

    db:
      image: "postgres:${POSTGRES_VERSION}"
      volumes:
        - datadb:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      ports:
        - 5432:5432

      psql:
        image: "postgres:${POSTGRES_VERSION}"
        links:
          - db
        environment:
          - PGPASSWORD=${POSTGRES_PASSWORD}
        command: psql -h db -U ${POSTGRES_USER} -d ${POSTGRES_DB}

      liquibase:
        links:
          - db

    volumes:
      datadb:
        name: postgres-data
